version: 2.1

orbs:
  ruby: circleci/ruby@2.5.3
  qlty: qltysh/qlty-orb@0.0.11

executors:
  default:
    docker:
      - image: cimg/ruby:3.4.3
      - image: cimg/postgres:17.5
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      CI: on
      PGHOST: localhost

jobs:
  doc:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec yard doc

  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m # Postgres
      - run: bundle exec rails db:test:prepare
      - ruby/rspec-test
      - qlty/coverage_publish:
          files: ./coverage/.resultset.json

  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  version: 2.1
  build:
    jobs:
      - doc
      - rspec
      - rubocop
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
